version: "3.7"

services:
  task-mgt-db:
    image: postgres:14
    container_name: task-mgt-db
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # volumes:
      # - /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
